version: "3.8"

services:
  php-apache:
    image: php:8.5-apache
    ports:
    - "80:80"
    volumes:
    - ./Server:/var/www/html/app/Server
    environment:
      - OPCACHE_ENABLE=0
    restart: always
  angular-client:
    build:
      context: ./Client
    ports:
      - "4200:80"
    restart: always